<?php 
session_start();
include '../database.php';

// Load employees and customers for the form

$customer = $connection->query("SELECT * FROM customer");

// Handle form submission
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Retrieve form data
    $customerID = $_POST['customerID'];
    $date = $_POST['date'];
    $time = $_POST['time'];
    $quantity = $_POST['quantity'];

    // Prepare and execute the insert query
    $stmt = $connection->prepare("INSERT INTO salestransaction (CustomerID, Date, Time, Quantity) VALUES (?, ?, ?, ?)");
    $stmt->bind_param("sssi", $customerID,  $date, $time, $quantity);

    if ($stmt->execute()) {
        $feedback = "Sales transaction added successfully.";
    } else {
        $feedback = "Error adding sales transaction: " . $stmt->error;
    }

    // Close the prepared statement
    $stmt->close();
}

?>

<!DOCTYPE html>
<html>
<head>
    <title>Add Sales Transaction - Local Bookstore</title>
    <link rel="stylesheet" type="text/css" href="../CSS/add.css">
</head>
<body>
    <h2>Add New Sales Transaction</h2>
    
    <button><a href="../sale_transaction.php">Back</a></button>

    <!-- Show feedback message -->
    <?php if (isset($feedback)) : ?>
        <p><?php echo htmlspecialchars($feedback); ?></p>
    <?php endif; ?>

    <form method="POST" action="add_transaction.php">
        <!-- Transaction ID is auto-generated by the database, so we don't need it in the form -->
        
        <label>Customer:</label><br>
        <select name="customerID" required>
            <option value="">Select a customer</option>
            <?php while($row = $customer->fetch_assoc()) { ?>
                <option value="<?php echo $row['CustomerID']; ?>"><?php echo $row['Name']; ?></option>
            <?php } ?>
        </select><br>

        <label>Date:</label><br>
        <input type="date" name="date" required><br>
        
        <label>Time:</label><br>
        <input type="time" name="time" required><br>

        <label>Quantity:</label><br>
        <input type="number" name="quantity" required><br>

        <input type="submit" value="Add Transaction">
    </form>
</body>
</html>
